const router=require('express').Router()
const user=require('../controller/userController')
const auth = require('../auth/auth')
const centre = require('../controller/centreController')

// const r = require('../r')
router.post('/login',user.login)
router.post('/twoFAVerfication',user.twoFAVerfication)
router.post('/signup',user.signup)
// router.post('/signupr',r.signupr)
router.post('/verifyOTP',user.verifyOTP)
router.post('/createSubAdmin', auth.verifyToken, user.createSubAdmin)
router.post('/permissionGranting', auth.verifyToken, user.permissionGranting)
router.post('/revokePermission', auth.verifyToken, user.revokePermission)
router.post('/twoFaRegister', auth.verifyToken, user.twoFaRegister)
router.delete('/deleteSubAdmin', auth.verifyToken, user.deleteSubAdmin)
router.get('/getUserList', auth.verifyToken, user.getUserList)
router.post('/bookSlot', auth.verifyToken, user.bookSlot)
router.post('/webhook', user.webhook)

router.post('/resendOTP', user.resendOTP)
router.post('/forgotPassword', user.forgotPassword)
router.post('/updatePassword', auth.verifyToken, user.updatePassword)
router.post('/resetPassword', auth.verifyToken, user.resetPassword)
router.post('/getUserProfile', auth.verifyToken, user.getUserProfile)
router.post('/deleteAccount', auth.verifyToken, user.deleteAccount)
router.post('/updateUserProfile', auth.verifyToken, user.updateUserProfile)
router.post('/updateEmail', auth.verifyToken, user.updateEmail)

router.post('/createCentre', auth.verifyToken, centre.createCentre)
router.put('/updateCentre', auth.verifyToken, centre.updateCentre)
router.post('/deleteCentre', auth.verifyToken, centre.deleteCentre)
router.get('/getCentreList', auth.verifyToken, centre.getCentreList)
router.get('/getSlotsList', auth.verifyToken, centre.getSlotsList)
// router.post('/addSlots', auth.verifyToken, centre.addSlots)

module.exports=router